name: Real Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Daily building Stage
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9
          format: 'YYYY-MM-DD HH-mm'

      - name: Create app json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        env:
          TIME: "${{ steps.time.outputs.time }}"
        with:
          name: "metadata.json"
          json: '{"appName": "shucle-driver-develop-daily-2021-01-19.apk", "version": "0.9.0.1", "updateDate": $TIME}'
    
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./metadata.json
    
      - name: Echo package.json
        run: echo ${{ steps.package.outputs.content }}
    
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
