name: Real Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Daily building Stage
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9
          format: 'YYYY-MM-DD HH-mm'

    - name: Create app json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        env:
          TIME: "${{ steps.time.outputs.time }}"
        with:
          name: "credentials.json"
          json: '{"appName": "shucle-driver-develop-daily-2021-01-19.apk", "version": "0.9.0.1", "updateDate": "TIME"}'
    
    - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
