name: Real Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Daily building Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9
          format: 'YYYY-MM-DD'
      - run: echo ${{steps.date.outputs.time}}

      - name: Get DateTime
        id: datetime
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9
          format: 'YYYY-MM-DD HH:mm'
      - run: echo ${{steps.datetime.outputs.time}}

      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './deploy-version.json'
          prop_path: 'versionName'
      - run: echo ${{steps.version.outputs.prop}} 

      - name: Create Metadata json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "metadata.json"
          json: '{"appName": "shucle-driver-${{ steps.date.outputs.time }}.apk", "version": "${{ steps.version.outputs.prop }}", "updateDate": "${{ steps.datetime.outputs.time }}"'
    
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./metadata.json
      - run: echo ${{ steps.package.outputs.content }}
